app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin'] );


// Authentication routes...
Route::get('auth/login',  ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
	// Department
    Route::resource('department', 'DepartmentController');
    Route::get('list', ['as' => 'admin.department.listDep', 'uses' => 'DepartmentController@listDep']);
    Route::post('savePdf', ['as' => 'savePdf', 'uses' => 'DepartmentController@savePdf']);
    Route::get('saveExcel', ['as' => 'saveExcel', 'uses' => 'DepartmentController@saveExcel']);

    // Staff
    Route::resource('staff','StaffController');
    Route::get('change-pass/{id}',['as' => 'admin.staff.getChange', 'uses' => 'StaffController@getChange']);
    Route::post('change-pass/{id}',['as' => 'admin.staff.postChange', 'uses' => 'StaffController@postChange']);
    
    //Review
    Route::resource('review', 'ReviewController');
    Route::get('add-colnum', ['as' => 'addColnum', 'uses' => 'ReviewController@addColnum']);
    
    //Level
    Route::resource('level', 'LevelController');
    Route::get('edit-review/{idReview}/{idStaff}',['as' => 'admin.review.editReview', 'uses' => 'ReviewController@editReview']);
    Route::resource('team', 'TeamController');

    // Position
    Route::resource('position', 'PositionController');
});

Route::any('{all}', function () {
    return view('errors.503');
});
Route::any('admin/{all}', function () {
    return view('errors.503');
});

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    protected $table = 'department';

    protected $fillable = ['id', 'name'];

    public $timestamps = false;

    public function staff(){
    	return $this->hasMany('App\Staff');
    }

}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use DB;
use App\Department;
use DOMPDF;
use Gate;
use App\StaffTeam;
use Auth;
use App\Team;
use App\Staff;
use Excel;
use App\Review;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $staff_team = '';
        $leader = '';
        $pie_leader= '';
        $department = '';
        
        $department = Department::leftJoin('staff', 'department.id', '=', 'staff.department_id')
                                ->join('level', 'staff.level_id', '=', 'level.id')
                                ->join('role', 'level.role_id', '=', 'role.id')
                                ->select(DB::raw('department.name as name_dep,role.name,count(*) as num'))
                                ->groupBy('department.name','role.name')
                                ->get()->toArray();
        $num_staff = $department;

        $pie = array();
        foreach ($department as $value) {
            $pie[$value['name_dep']][] = array($value['name'] , (int)$value['num']);
        }

        // is Leader
        if (Gate::allows('check-leader')) {
            $department = Department::leftJoin('staff', 'department.id', '=', 'staff.department_id')
                                ->join('level', 'staff.level_id', '=', 'level.id')
                                ->join('role', 'level.role_id', '=', 'role.id')
                                ->select(DB::raw('department.name as name_dep,role.name,count(*) as num'))
                                ->where(['department.id' => Auth::user()->department_id, 'department.active' => 1])
                                ->groupBy('department.name','role.name')
                                ->get()->toArray();
            $num_staff = $department;

            $pie = array();
            foreach ($department as $value) {
                $pie[$value['name_dep']][] = array($value['name'] , (int)$value['num']);
            }

        }
        

        // is Developer
        // if is manager / != department / yourself 
        // denied
        if (Gate::allows('check-developer')) {
            // get team of staff
            $staff = StaffTeam::where('staff_id', Auth::user()->id)->get()->first();
            if(isset($staff) && !empty($staff)){
                $staff_team = StaffTeam::where('team_id', $staff->team_id)->where('staff_id', '!=', Auth::user()->id)->get();
                $team = Team::where('id', $staff->team_id)->get()->first();
                $leader = Staff::find($team->creator);
            }
            // staff in department
            $staff_department = Staff::where(['active' => 1, 'department_id' => Auth::user()->department_id])->get();
           
        }                        
        return view('admin.department.home', compact('pie', 'staff_team', 'leader', 'num_staff', 'staff_department'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function listDep(){
        $dep = Department::all();
        return view('admin.department.list', compact('dep'));
    }
    public function create()
    {
        return view('admin.department.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'txtName' => 'required',
            'rActive' => 'required|in:0,1',
        ]);
        $dep = New Department();
        $dep->name = $request->txtName;
        $dep->active = $request->rActive;
        $dep->save();

        return redirect()->route('admin.department.listDep')->with('message', 'Create Department success!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $department = Department::find($id);
        return view('admin.department.update', compact('department'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'txtName' => 'required',
            'rActive' => 'required|in:0,1',
        ]);
        $dep = Department::find($id);
        $dep->name = $request->txtName;
        $dep->active = $request->rActive;
        $dep->save();

        return redirect()->route('admin.department.listDep')->with('message', 'Update Department success!');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dep = Department::find($id);
        $dep->delete();
        return redirect()->route('admin.department.listDep')->with('message', 'Delete Department success!');

    }
    public function savePdf(){
        if (isset($_POST['htmlContent']) && $_POST['htmlContent'] != '')
        {
            if(Auth::user()->level->role->name == 'Manager'){
                $department = Department::leftJoin('staff', 'department.id', '=', 'staff.department_id')
                                ->join('level', 'staff.level_id', '=', 'level.id')
                                ->join('role', 'level.role_id', '=', 'role.id')
                                ->select(DB::raw('department.name as name_dep,role.name,count(*) as num'))
                                ->groupBy('department.name','role.name')
                                ->get()->toArray();
            }
            if(Auth::user()->level->role->name == 'TeamLeader'){
                $department = Department::leftJoin('staff', 'department.id', '=', 'staff.department_id')
                                    ->join('level', 'staff.level_id', '=', 'level.id')
                                    ->join('role', 'level.role_id', '=', 'role.id')
                                    ->select(DB::raw('department.name as name_dep,role.name,count(*) as num'))
                                    ->where(['department.id' => Auth::user()->department_id, 'department.active' => 1])
                                    ->groupBy('department.name','role.name')
                                    ->get()->toArray();
            }
            

            require_once 'public/dompdf/dompdf_config.inc.php';
         
            $file_name = 'Elisoft_Chart.pdf';

            $html = '<html>
                                <head>
                                    <style>
                                        img{
                                            width:335px;
                                            float:left;
                                            margin:10px;
                                        }
                                        .title{
                                            color:red;
                                            text-align: center;
                                            margin-bottom: 50px;
                                        }
                                        .table-staff{
                                            border: 2px;
                                            text-align:center;
                                        }
                                        .table-staff tr th{
                                            background-color: #DDD;
                                            padding: 5px 30px 5px 30px;
                                        }
                                        .table-staff tr td{
                                            padding: 5px 30px 5px 30px;
                                        }
                                    </style>
                                </head>
                                <body>
                                    <h1 class="title"> ELISOFT STAFF MANAGER </h1>
                                    <h3>1. Summary Chart</h3>
                                ';

            $html = $html.$_POST['htmlContent'];
            
            $html = $html.'
                                <h3>2. Table </h3>
                                    <table class="table-staff" border="1">
                                        <tr>
                                            <th>Department</th>
                                            <th>Role</th>
                                            <th>Quantity</th>
                                        </tr>
                                        
                                            ';
                                            foreach ($department as $key => $value) {
                                                $html = $html.'<tr><td>'.$value["name_dep"].'</td>';
                                                $html = $html.'<td>'.$value["name"].'</td>';
                                                $html = $html.'<td>'.$value["num"].'</td></tr>';
                                            }
            $html = $html.'                                
                                        
                                    </table>

                                

                                </body>
                            </html>';
                   
            $dompdf = new DOMPDF();
            $dompdf->load_html($html);
            $dompdf->render();

resources/views/admin/department/create.blade.php
@extends('admin.master')
@section('title')
Create Department
@endsection
@section('content')
<form class="form-horizontal" method="POST" action="{{ route('admin.department.store') }}">
	<input type="hidden" name="_token" value="{{ csrf_token() }}" >
	<div class="form-group form-group-sm">
    	<label class="col-sm-1"></label>
    	<div class="col-sm-7">
    		@if (count($errors) > 0)
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Name</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtName" type="text" id="formGroupInputSmall" value="{{ old('txtName') }}" placeholder="Enter Name Here ...">
    	</div>
    </div>
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
             Active <input type="radio" name="rActive" id="optionsRadios1" value="1" checked>
        </div>
        <div class="col-sm-2">
             DeActive <input type="radio" name="rActive" id="optionsRadios1" value="0">
        </div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall"></label>
    	<div class="col-sm-6">
      		<button class="btn btn-primary" name="btnSubmit" style="width:100px">Create</button>
    	</div>
    </div>
  
</form>
@endsection

resources/views/admin/department/home.blade.php
@extends('admin.master')
@section('title')
DashBoard
@endsection
@section('content')
@if(Session::has('message'))
    <div id="message" class="alert alert-success">
        {{ Session::get('message') }}
    </div>
@endif


@can('check-developer')
	<div class="row">
	    <div class="col-lg-12">
	        <div class="alert alert-success">
                <label>Average score : {{ \App\Providers\AvgProvider::average(Auth::user()->id)?\App\Providers\AvgProvider::average(Auth::user()->id):'0' }}</label>
            </div>
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <label>List Staff Team</label>
	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">
	                <div class="dataTable_wrapper">
	                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
	                        <thead>
	                            <tr>
	                                <th>Name</th>
	                                <th> Average score </th>
	                                <th>Level</th>
	                                <th>Review</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                        	@if(isset($leader) && !empty($leader))
	                        		<tr>
		                        		<td class="leader">&nbsp;<a href="javascript:void(0)" style="color:red;" class="btn btn-link tooltip-staff" data-toggle="tooltip" data-html="true" data-placement="top" title="Phone:0{{ $leader->phone }} <br>  Email:{{ $leader->email }}">{{ $leader->name }} (BOSS)</a></td>
		                        		<td style="text-align:center">{{ \App\Providers\AvgProvider::average($leader->id)?\App\Providers\AvgProvider::average($leader->id):'0' }}</td>
		                        		<td>{{ $leader->level->name }}</td>
		                        		<td style="text-align:center">
		                                   	<label>
		                                   		<button class="btn btn-link"><a href="{{ route('admin.review.show', $leader->id) }}"><i class="fa fa-thumbs-up"></i></a></button> &nbsp;&nbsp;&nbsp;
		                                    </label>
		                                </td>
		                        	</tr>
	                        	@endif
	                            @if(isset($staff_team) && !empty($staff_team))
	                            	@foreach($staff_team as $staff_team)
		                                <tr class="odd gradeX">
		                                	<td><button class="btn btn-link tooltip-staff" data-toggle="tooltip" data-html="true" data-placement="top" title="Phone:0{{ $staff_team->staff->phone }} <br>  Email:{{ $staff_team->staff->email }}">{{ $staff_team->staff->name }}</button></td>
		                                    <td style="text-align:center">{{ \App\Providers\AvgProvider::average($staff_team->staff->id)?\App\Providers\AvgProvider::average($staff_team->staff->id):'0' }}</td>
		                                    <td>{{ $staff_team->staff->level->name }}</td>
		                                    <td style="text-align:center">
		                                       	<label>
		                                            <button class="btn btn-link"><a href="{{ route('admin.review.show', $staff_team->staff->id) }}"><i class="fa fa-thumbs-up"></i></a></button> &nbsp;&nbsp;&nbsp;
		                                        </label>
		                                    </td>
		                                </tr>
		                            @endforeach
	                            @endif
	                        </tbody>
	                    </table>
	                </div>
	                <!-- /.table-responsive -->
	            </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->

	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <label>Other Staff In Department</label>
	            </div>
	            <!-- /.panel-heading -->
	            <div class="panel-body">
	                <div class="dataTable_wrapper">
	                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
	                        <thead>
	                            <tr>
	                                <th>Name</th>
	                                <th>Level</th>
	                                <th>Review</th>
	                            </tr>
	                        </thead>
	                        <tbody>
	                        	@if(isset($staff_department) && !empty($staff_department))
	                        	<?php  ?>
	                            	@foreach($staff_department as $staff_department)
		                                <tr class="odd gradeX">
		                                	<td><button class="btn btn-link tooltip-staff" data-toggle="tooltip" data-html="true" data-placement="top" title="Phone:0{{ $staff_department->phone }} <br>  Email:{{ $staff_department->email }}">{{ $staff_department->name }}</button></td>
		                                    <td>{{ $staff_department->level->name }}</td>
		                                    <td style="text-align:center">
		                                       	<label>
		                                            <button class="btn btn-link"><a href="{{ route('admin.review.show', $staff_department->id) }}"><i class="fa fa-thumbs-up"></i></a></button> &nbsp;&nbsp;&nbsp;
		                                        </label>
		                                    </td>
		                                </tr>
		                            @endforeach
	                            @endif
	                        </tbody>
	                    </table>
	                </div>
	                <!-- /.table-responsive -->
	            </div>
	            <!-- /.panel-body -->
	        </div>
	        <!-- /.panel -->
	    </div>
	    <!-- /.col-lg-12 -->
	</div>
	<!-- /.row -->


@else

<div class="panel panel-default">
    <div class="panel-heading">
        <label>Number Staff In Department</label>
    </div>
    @if(Auth::user()->level->role_id == 2 || Auth::user()->level->role_id == 3 )
	    <div class="export pull-right">
		    <form method='post' action="{{ route('savePdf') }}" id='savePDFForm'>
				<input type="hidden" name="_token" value="{{ csrf_token() }}">
			 	<input type='hidden' id='htmlContentHidden' name='htmlContent' value='htmlContentHidden'>
			 	<a href="{{ route('saveExcel') }}"><input type='button' class="btn btn-default" id="save-excel" value='Save to Excel'></a>
			 	<input type='button' class="btn btn-default" id="downloadBtn" value='Save to PDF'>
			</form>
		</div>
	@endif
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Department</th>
                        <th>Role</th>
                        <th>Number</th>
                    </tr>
                </thead>
                <tbody>
                	@foreach($num_staff as $num)
	                    <tr>
	                    	<td>{{ $num['name_dep'] }}</td>
	                    	<td>{{ $num['name'] }}</td>
	                    	<td>{{ $num['num'] }}</td>
	                    </tr>
                   	@endforeach
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->


<div class="row">
<?php
	$stt = 0;
	$pie_2 = array();
	foreach ($pie as $key => $pie_chart) {
		$pie_2 = $pie_chart;
		$stt++;
		$pie_chart = json_encode($pie_chart);
   		
        $HTML =<<<XYZ
        <script type="text/javascript">
	      	google.load("visualization", "1", {packages:["corechart"]});
	      	google.setOnLoadCallback(drawChart);
	      	function drawChart() {
		        var data = new google.visualization.DataTable();
		          	data.addColumn('string', 'Age Range');
		          	data.addColumn('number', 'Number');
		          	data.addRows({$pie_chart});
	        

		        var options = {
		          	title: "$key",
		          	is3D: true,
		          	backgroundColor: '#CCC',
		          	width: 500,
        			height: 400,
        			fontSize: 16,
        			titleTextStyle:{ 
        				color: 'red',
        				fontSize: 20,
					},
					chartArea:{left:30,top:30,width:'80%',height:'80%'}
		          	
		        };

		        // Instantiate and draw our chart, passing in some options.
		        var chart_div = document.getElementById('$stt');
		        var chart = new google.visualization.PieChart(chart_div);
		 		
		        var chart_div_final = document.getElementById('a$stt');
		        var chart_final = new google.visualization.PieChart(chart_div_final);
		        // Wait for the chart to finish drawing before calling the getIm geURI() method.
		        google.visualization.events.addListener(chart, 'ready', function () {
		         chart_div_final.innerHTML = '<img src="' + chart.getImageURI() + '">';
		        });

		        chart.draw(data, options);
		        
		    }
	      	// Make the charts responsive
		    jQuery(document).ready(function(){
		        jQuery(window).resize(function(){
		          	drawChart();
		        });
		    });
	    </script>

		<div id="$stt" style="float:left !important; border:2px solid #AEA; border-radius:5px; margin:10px"></div>
		<div id="a$stt" style="display:none"></div>

XYZ;
echo $HTML;

}
?>
</div>
<?php
	// push image
	echo '<script>
	jQuery(document).ready(function() {
	    jQuery("#downloadBtn").on("click", function() {
	    	var htmlContent = "";
	    ';

	    for($i = 1; $i <= $stt; $i++){
	    	echo 'var htmlContent'.$i.' = jQuery("#a'.$i.'").html();';
	    	echo 'htmlContent = htmlContent + htmlContent'.$i.';';
		}

	    echo 'jQuery("#htmlContentHidden").val(htmlContent);
				
	        // submit the form
	        jQuery("#savePDFForm").submit();
	    });
	  });
	</script>';
	
	
?>

@endcan







@endsection

resources/views/admin/department/list.blade.php
@extends('admin.master')
@section('title')
Level
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12">
        @if(Session::has('message'))
            <div id="message" class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <div class="panel panel-default">
            <div class="panel-heading danger">
                <p style="color:#337ab7">Department</p>
            </div>
            
            <!-- /.panel-heading -->
            <div class="row">
                <div class="col-sm-6" style="margin-top:10px; margin-left:10px">
                    
                 </div>
             </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped"  id="dataTables-example">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><a href="">Name </a></th>
                                <th style="text-align:center"><a href="">Status</a></th>
                                <th style="text-align:center"><a href="">Action</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $stt=1; ?>
                            @foreach($dep as $key => $value)
                                <tr>
                                    <td>{{ $stt }}</td>
                                    <td>{{ $value->name }}</td>
                                    <th><?php echo $value->active==1?'Active':'DeActive' ?></th>
                                    <td style="text-align:center">
                                        <label>
                                            <button class="btn btn-link"><a href="{{ route('admin.department.edit', $value->id) }}"><i class="glyphicon glyphicon-pencil"></i></a></button> &nbsp;&nbsp;&nbsp;
                                        </label>
                                        <label>
                                            {!! Form::open( array( 'route' => array('admin.department.destroy',$value->id), 'method' => 'DELETE' ) ) !!}
                                                <button onclick="return deleteConfirm('You want delete?')" type="submit"  class="btn btn-link" ><i class="glyphicon glyphicon-remove"></i></button>
                                            {!! Form::close() !!}
                                        </label>
                                    </td>
                                </tr>
                                <?php $stt++ ?>
                            @endforeach

                        </tbody>
                    </table>
                    
                </div>
                <!-- /.table-responsive -->
                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@endsection

resources/views/admin/department/update.blade.php
@extends('admin.master')
@section('title')
Create Department
@endsection
@section('content')
<form class="form-horizontal" method="POST" action="{{ route('admin.department.update', $department->id) }}">
	<input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="_token" value="{{ csrf_token() }}" >
	<div class="form-group form-group-sm">
    	<label class="col-sm-1"></label>
    	<div class="col-sm-7">
    		@if (count($errors) > 0)
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
    	</div>
    </div>
   
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Name</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtName" type="text" id="formGroupInputSmall" value="{{ old('txtName',$department->name?$department->name:'')  }}">
    	</div>
    </div>
    
    
    
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
             Active <input type="radio" name="rActive" id="optionsRadios1" value="1" <?php echo ($department->active==1)?'checked':'' ?> >
        </div>
        <div class="col-sm-2">
             DeActive <input type="radio" name="rActive" id="optionsRadios1" value="0" <?php echo ($department->active==0)?'checked':'' ?> >
        </div>
    </div>

    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall"></label>
    	<div class="col-sm-6">
      		<button class="btn btn-primary" name="btnSubmit" style="width:100px">Update</button>
    	</div>
    </div>
  
</form>
@endsection