app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin'] );


// Authentication routes...
Route::get('auth/login',  ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
	// Department
    Route::resource('department', 'DepartmentController');
    Route::get('list', ['as' => 'admin.department.listDep', 'uses' => 'DepartmentController@listDep']);
    Route::post('savePdf', ['as' => 'savePdf', 'uses' => 'DepartmentController@savePdf']);
    Route::get('saveExcel', ['as' => 'saveExcel', 'uses' => 'DepartmentController@saveExcel']);

    // Staff
    Route::resource('staff','StaffController');
    Route::get('change-pass/{id}',['as' => 'admin.staff.getChange', 'uses' => 'StaffController@getChange']);
    Route::post('change-pass/{id}',['as' => 'admin.staff.postChange', 'uses' => 'StaffController@postChange']);
    
    //Review
    Route::resource('review', 'ReviewController');
    Route::get('add-colnum', ['as' => 'addColnum', 'uses' => 'ReviewController@addColnum']);
    
    //Level
    Route::resource('level', 'LevelController');
    Route::get('edit-review/{idReview}/{idStaff}',['as' => 'admin.review.editReview', 'uses' => 'ReviewController@editReview']);
    Route::resource('team', 'TeamController');

    // Position
    Route::resource('position', 'PositionController');
});

Route::any('{all}', function () {
    return view('errors.503');
});
Route::any('admin/{all}', function () {
    return view('errors.503');
});

app/Staff.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class Staff extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{

    use Authenticatable, Authorizable, CanResetPassword;

    
    protected $table = 'staff';

    protected $fillable = ['name', 'birth', 'position_id', 'level_id', 'phone', 'department_id', 'email'];

    public $timestamps = false;

    protected $hidden = ['password', 'remember_token'];


    public function position(){
    	return $this->belongsTo('App\Position', 'position_id');
    }

    public function level(){
    	return $this->belongsTo('App\Level', 'level_id');
    }

    public function department(){
    	return $this->belongsTo('App\Department', 'department_id');
    }

    public function team(){
        return $this->belongsToMany('App\Team', 'staff_team');
    }

    public function staff_team(){
        return $this->hasMany('App\StaffTeam', 'staff_id');
    }
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Level;
use App\Department;
use App\Position;
use App\Staff;
use App\Http\Requests\StaffCreateRequest;
use App\Http\Requests\UpdateStaffRequest;
use Mail;
use Hash;
use Gate;
use Auth;
use DB;
use Input;
use App\Review;
use App\StaffTeam;

class StaffController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sort = $request->get('sort');
        $sort = max($sort, 1);
        $qty = $request->get('show');
        $qty = max($qty, 10);
        $dep = (int)$request->get('dep');
        $sorts = array(1=>['name' => 'asc'],['name' => 'desc']);
        $department = '';

        // is manager
        // show all staff 
        if (Gate::allows('check-manager')) {
            $staff = Staff::where('level_id', '!=', 6)->orderBy(key($sorts[$sort]), current($sorts[$sort]))
                        ->paginate($qty);
            if(isset($dep) && !empty($dep)){
                $staff = Staff::where('level_id', '!=', 6)->where('department_id', $dep)
                        ->orderBy(key($sorts[$sort]), current($sorts[$sort]))
                        ->paginate($qty);
            }      
            $department = Department::where('active', 1)->get();
        }
        // is leader
        // show staff in department 
        if(Gate::allows('check-leader')){
            $staff = Staff::where('level_id', '!=', 6)->where('department_id', Auth::user()->department_id)->orderBy(key($sorts[$sort]), current($sorts[$sort]))
                        ->paginate($qty);

        }
        // is admin
        // show all staff 
        if(Gate::allows('check-admin')){
            $staff = Level::where('active',1)->where('role_id', 2)->orWhere('role_id', 3)->get();
        }
        // is developer
        // denied
        if (Gate::allows('check-developer')) {
            return redirect()->route('admin.department.index');
        }
        
        if(Auth::user()->level->role_id == 2 || Auth::user()->level->role_id == 3){
            $staff->setPath('staff');
            $staff->appends('show',$qty);
            if(!empty($dep)){
                $staff->appends('dep',$dep);
            }
        }
        

        return view('admin.staff.list', compact('staff', 'department'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $position = Position::where('active',1)->get();
        // is manager
        // create staff with role = Developer or Leader
        // department = all
        if (Gate::allows('check-manager')) {
            $level = Level::where(['role_id'=> 3, 'active' => 1])->orWhere(['role_id'=> 4, 'active' => 1])->get();
            $department = Department::where('active',1)->get();
        }
        // is leader
        // create staff with role = Developer
        // department = department leader
        else if(Gate::allows('check-leader')){
            $level = Level::where('role_id', 4)->where('active',1)->get();
            $department = Department::where('id', Auth::user()->department_id)->where('active',1)->get()->first();
        }
        // is admin
        // create staff with role = Manager or Leader
        // department = all
        else if(Gate::allows('check-admin')){
            $department = Department::where('active',1)->get();
            $level = Level::where(['role_id'=> 2, 'active' => 1])->orWhere(['role_id'=> 3, 'active' => 1])->get();
        }
        // is dev
        // denied
        else {
            return redirect()->route('admin.department.index');
        }
        
        return view('admin.staff.create', compact('level', 'department', 'position'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StaffCreateRequest $request)
    {
        $position = $request->position;
        // is manager
        // department all
        if (Gate::allows('check-manager')) {
            $this->validate($request,[
                'department' => 'required|numeric',
            ]);
            $department = $request->department;
        }

        //is leader
        // department = department of leader
        else if(Gate::allows('check-leader')){
            $department = Auth::user()->department_id;
        }

        //is admin
        // department all
        else if(Gate::allows('check-admin')){
            $this->validate($request,[
                'department' => 'required|numeric|not_in:0',
            ]);
            $temp = (int)$request->level;
            $role = Level::find($temp);
            // is manager
            // department = 0
            // position = 0
            if($role->role_id == 2){
                $department = 0;
                $position = 0;
            }
            else{
                $department = $request->department;
            }
            
        }

        //is developer
        else {
            return redirect()->route('admin.department.index')->with('message', 'Access is Denied!');
        }

        $birth = date('Y-m-d', strtotime($request->txtBirth));
        $password = str_random(6);
        $staff = new Staff();
        $staff->name = $request->txtName;
        $staff->birthday = $birth;
        $staff->position_id = $position;
        $staff->level_id = $request->level;
        $staff->email = $request->txtEmail;
        $staff->password = Hash::make($password);
        $staff->phone = $request->txtPhone;
        $staff->department_id = $department;
        $staff->active = $request->rActive;
        $staff->save();

        Mail::send('emails.register', ['password' => $password], function ($m) use ($staff) {
            $m->from('tachikien2012@gmail.com', 'Elisoft Staff Manager');

            $m->to($staff->email)->subject('Your Password Register !');
        });

        return redirect()->route('admin.staff.index')->with('message', 'Add staff success!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         
        $position = Position::where('active',1)->get();
        // if is Leader
        // if staff edit != dev or yourself => denied
        if(Gate::allows('check-leader')){
            $staff = Staff::find($id)->level->role;
            if($staff->name != "Developer" && $id != Auth::user()->id){
                return redirect()->route('admin.staff.index')->with('message', 'Access is denied');
            }else{
                $level = Level::where('role_id', 4)->get();
                $department = Department::where('id', Auth::user()->department_id)->where('active', 1)->get()->first();
            }
        }
        //if is Admin
        // if staff = dev => denied
        else if(Gate::allows('check-admin')){
            $staff = Staff::find($id)->level->role;
            if($staff->name == "Developer" && $id != Auth::user()->id){
                return redirect()->route('admin.staff.index')->with('message', 'Access is denied');
            }
            else{
                $department = Department::where('active', 1)->get();
                $level = Level::where(['role_id'=> 2, 'active' => 1])->orWhere(['role_id'=> 3, 'active' => 1])->get();
            }
        }

        //is manager
        // if staff = manager => denied
        else if (Gate::allows('check-manager')) {
            $staff = Staff::find($id)->level->role;
            if($staff->name == "Manager" && $id != Auth::user()->id){
                return redirect()->route('admin.staff.index')->with('message', 'Access is denied');
            }
            else{
                $level = Level::where('role_id', 3)->orWhere('role_id', 4)->get();
                if($id == Auth::user()->id){
                    $department = '';
                }
                $department = Department::where('active', 1)->get();
            }

        }

        //is developer
        // only edit profile yourself
        else{
            $staff_id = Auth::user()->id;

            if($staff_id != $id){
                return redirect()->route('admin.staff.index')->with('message', 'Access is denied');
            }else{
                $position = Position::where('id', Auth::user()->position_id)->where('active', 1)->get();
                $level = Level::where('id', Auth::user()->level_id)->where('active', 1)->get();
                $department = Department::where('id', Auth::user()->department_id)->where('active', 1)->get()->first();
            }
        }
        if($id == Auth::user()->id){
            $check_account = 1;
        }
        else{
            $check_account = 0;
        }

        
        $staff = Staff::find($id);
        return view('admin.staff.update', compact('id','staff', 'position', 'level', 'department', 'check_account'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStaffRequest $request, $id)
    {
        $department = $request->department;
        $position = $request->position;
        $level = $request->level;

        //is manager
        if (Gate::allows('check-manager')) {
            $this->validate($request,[
                'department' => 'required|numeric|not_in:0',
            ]);

resources/views/admin/staff/create.blade.php
@extends('admin.master')
@section('title')
Create Staff
@endsection
@section('content')
<form class="form-horizontal" method="POST" action="{{ route('admin.staff.store') }}">
	<input type="hidden" name="_token" value="{{ csrf_token() }}" >
	<div class="form-group form-group-sm">
    	<label class="col-sm-1"></label>
    	<div class="col-sm-7">
    		@if (count($errors) > 0)
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Name</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtName" type="text" id="formGroupInputSmall" value="{{ old('txtName') }}" placeholder="Enter Name Here ...">
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Email</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtEmail" type="text" value="{{ old('txtEmail') }}" id="formGroupInputSmall" placeholder="Enter Email Here ...">
    	</div>
    </div>
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label" for="formGroupInputSmall">Phone</label>
        <div class="col-sm-6">
            <input class="form-control" name="txtPhone" type="text" value="{{ old('txtPhone') }}" id="formGroupInputSmall" placeholder="Enter Email Here ...">
        </div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Birth</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtBirth" type="text" id="datepicker" id="formGroupInputSmall" value="{{ old('txtBirth') }}" placeholder="Enter Birth Here ..." readonly style="background-color:#FFF" >
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Position</label>
    	<div class="col-sm-6">
      		<select class="form-control" name="position">
      		 	<option value="0">  ------  </option>
			    @if($position)
				    @foreach($position as $key => $value)
				    	<?php echo '<option value="'.$value['id'].'" > '.$value['name'].' </option>' ?>
				    @endforeach
			    @endif
			</select>
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Level</label>
    	<div class="col-sm-6">
      		<select class="form-control" name="level">
			    <option value="0">  ------  </option>
			    @if($level)
				    @foreach($level as $key => $value)
				    	<?php echo '<option value="'.$value['id'].'" > '.$value['name'].' </option>' ?>
				    @endforeach
			    @endif
			</select>
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Department</label>
    	<div class="col-sm-6">
      		<select class="form-control" name="department">
			    <option value="0">  ----- </option>
			    @if($department)
                    @can('check-admin')
                        @foreach($department as $key => $value)
                            <?php echo '<option value="'.$value['id'].'" > '.$value['name'].' </option>' ?>
                        @endforeach
                    @endcan
                    @can('check-manager')
    				    @foreach($department as $key => $value)
    				    	<?php echo '<option value="'.$value['id'].'" > '.$value['name'].' </option>' ?>
    				    @endforeach
                    @endcan
                    @can('check-leader')
                        <option value="{{ $department->id }}">  {{ $department->name }} </option>
                    @endcan
			    @endif
			</select>
    	</div>
    </div>
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
             Active <input type="radio" name="rActive" id="optionsRadios1" value="1" checked>
        </div>
        <div class="col-sm-2">
             DeActive <input type="radio" name="rActive" id="optionsRadios1" value="0">
        </div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall"></label>
    	<div class="col-sm-6">
      		<button class="btn btn-primary" name="btnSubmit" style="width:100px">Create</button>
    	</div>
    </div>
  
</form>
@endsection

resources/views/admin/staff/list.blade.php
@extends('admin.master')
@section('title')
List Staff
@endsection
@section('content')

@can('check-admin')

<div class="row">
    <div class="col-lg-12">
        @if(Session::has('message'))
            <div id="message" class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <div class="panel panel-default">
            <div class="panel-heading">
                <label>List Staff (Manager - Leader)</label>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Position</th>
                                <th>Level</th>
                                <th>Department</th>
                                <th style="text-align:center">Status</th>
                                <th style="text-align:center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($staff as $staff)
                            @foreach($staff->staff as $value)
                                <tr class="odd gradeX">
                                    <td>{{ $value->name }}</td>
                                    <td>{{ isset($value->position->name)?$value->position->name:'None' }}</td>
                                    <td>{{ $value->level->name }}</td>
                                    <td>{{ isset($value->department->name)?$value->department->name:'None' }}</td>
                                    <th><?php echo $value->active==1?'Active':'DeActive' ?></th>
                                    <td style="text-align:center">
                                        <label>
                                            <button class="btn btn-link"><a href="{{ route('admin.staff.edit', $value->id) }}"><i class="glyphicon glyphicon-pencil"></i></a></button> &nbsp;&nbsp;&nbsp;
                                        </label>
                                        <label>
                                            {!! Form::open( array( 'route' => array('admin.staff.destroy',$value->id), 'method' => 'DELETE' ) ) !!}
                                                <button onclick="return deleteConfirm('Bạn chắc chắn muốn xóa?')" type="submit"  class="btn btn-link" ><i class="glyphicon glyphicon-remove"></i></button>
                                            {!! Form::close() !!}
                                        </label>
                                    </td>
                                </tr>
                            @endforeach
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

@else
<div class="row">
    <div class="col-lg-12">
        @if(Session::has('message'))
            <div id="message" class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <div class="panel panel-default">
            <div class="panel-heading danger">
                <p style="color:#337ab7">{{ $staff->total() }} Staffs / {{ $staff->lastPage() }} Pages</p>
            </div>
            <?php
                $sort=Request::input('sort');
                $qty = Request::input('show');
                $dep = Request::input('dep');
                $staff->appends('sort', $sort==1?2:1);
                $nameUrl = $staff->url($staff->currentPage());

                

                $staff->appends('sort', $sort);
                $nameImg = '';
                if($sort == 1)
                    $nameImg = "<i class='glyphicon glyphicon-triangle-bottom'></i>";
                if($sort == 2)
                    $nameImg = "<i class='glyphicon glyphicon-triangle-top'></i>";
            ?>
            <!-- /.panel-heading -->
            <div class="row">
                <div class="col-sm-4" style="margin-top:10px; padding-left:50px">
                    <form name="frmShow" action="{{ route('admin.staff.index') }}" method="GET">
                        <input name="dep" type="hidden" value="{{ $dep?$dep:'' }}">
                        <div class="dataTables_length">
                            <label>Show 
                                <select name="show" class="form-control" onchange="submitForm(this)">
                                    <option value="10" <?php echo $qty==10?'selected':'' ?> > 10 </option>
                                    <option value="25" <?php echo $qty==25?'selected':'' ?> > 25 </option>
                                    <option value="50" <?php echo $qty==50?'selected':'' ?> > 50 </option>
                                    <option value="100" <?php echo $qty==100?'selected':'' ?> > 100 </option>
                                </select>
                             entries</label>
                        </div>
                     </form>
                </div>
                @can('check-manager')
                <div class="col-sm-4" style="margin-top:10px">
                    <form name="frmShow" action="{{ route('admin.staff.index') }}" method="GET">
                        <input name="show" type="hidden" value="{{ $qty?$qty:'' }}">
                        <div class="dataTables_length">
                            <label>Department
                                <select name="dep" class="form-control" onchange="submitFormDepartment(this)" style="min-width:100px">
                                    <option value=" "> --------- </option>
                                    @foreach($department as $department)
                                        <?php
                                            echo '<option value="'.$department->id.'"';
                                            echo $dep==$department->id?'selected':'';
                                            echo '>'.$department->name.'</option>';
                                        ?>
                                    @endforeach
                                </select> 
                            </label>
                        </div>
                     </form>
                 </div>
                 @endcan
             </div>
        
            

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><a href="{{ $nameUrl }}">Name {!! $nameImg !!}</a></th>
                                <th><a href="{{ $nameUrl }}">Position {!! $nameImg !!}</a></th>
                                <th><a href="{{ $nameUrl }}">Level {!! $nameImg !!}</a></th>
                                <th><a href="{{ $nameUrl }}">Department {!! $nameImg !!}</a></th>
                                <th style="text-align:center">Average Score</th>
                                <th style="text-align:center">Status</th>
                                <th style="text-align:center">Action</th>
                                <th style="text-align:center">Review</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $stt=1; ?>
                            @foreach($staff as $key => $value)
                                <tr>
                                    <td>{{ $stt }}</td>
                                    <td><button class="btn btn-link tooltip-staff" data-toggle="tooltip" data-html="true" data-placement="top" title="Phone:0{{ $value->phone }} <br>  Email:{{ $value->email }}">{{ $value->name }}</button></td>
                                    <td>{{ isset($value->position->name)?$value->position->name:'None' }}</td>
                                    <td>{{ $value->level->name }}</td>
                                    <td>{{ isset($value->department->name)?$value->department->name:'None' }}</td>
                                    <td>{{ \App\Providers\AvgProvider::average($value->id)?\App\Providers\AvgProvider::average($value->id):'0' }}</td>
                                    <th><?php echo $value->active==1?'Active':'DeActive' ?></th>
                                    <td style="text-align:center">
                                        <label>
                                            <button class="btn btn-link"><a href="{{ route('admin.staff.edit', $value->id) }}"><i class="glyphicon glyphicon-pencil"></i></a></button> &nbsp;&nbsp;&nbsp;
                                        </label>
                                        <label>
                                            {!! Form::open( array( 'route' => array('admin.staff.destroy',$value->id), 'method' => 'DELETE' ) ) !!}
                                                <button onclick="return deleteConfirm('You want delete?')" type="submit"  class="btn btn-link" ><i class="glyphicon glyphicon-remove"></i></button>
                                            {!! Form::close() !!}
                                        </label>
                                    </td>
                                    <td style="text-align:center">
                                        <label>
                                            <button class="btn btn-link"><a href="{{ route('admin.review.show', $value->id) }}"><i class="glyphicon glyphicon-saved"></i></a></button> &nbsp;&nbsp;&nbsp;
                                        </label>
                                    </td>
                                </tr>
                                <?php $stt++ ?>
                            @endforeach

                        </tbody>
                    </table>
                    <div class="pull-right">
                        <nav>
                            <ul class="pagination">
                                @if( $staff->currentPage() > 1 )
                                    <li>
                                        <a href="{{ $staff->url(1) }}" aria-label="Previous">
                                            <span aria-hidden="true">First</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ $staff->url($staff->currentPage()-4 ) }}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                @endif
                                @for($i = 1; $i <= $staff->lastPage(); $i++)
                                    @if($i <= $staff->currentPage()+3 && $i >= $staff->currentPage()-3)
                                        <li class="<?php echo $i==$staff->currentPage()?'active':'' ?>"><a href="{{ $staff->url($i) }}">{{ $i }}</a></li>
                                    @endif
                                @endfor
                                @if($staff->currentPage()+3 < $staff->lastPage())
                                    <li>
                                        <a href="{{ $staff->url($staff->currentPage()+4 ) }}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{{ $staff->url($staff->lastPage()) }}" aria-label="Previous">
                                            <span aria-hidden="true">End</span>
                                        </a>
                                    </li>
                                @endif
                            </ul>
                        </nav>
                    </div>
                    
                </div>
                <!-- /.table-responsive -->
                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@endcan
@endsection