app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin'] );


// Authentication routes...
Route::get('auth/login',  ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
	// Department
    Route::resource('department', 'DepartmentController');
    Route::get('list', ['as' => 'admin.department.listDep', 'uses' => 'DepartmentController@listDep']);
    Route::post('savePdf', ['as' => 'savePdf', 'uses' => 'DepartmentController@savePdf']);
    Route::get('saveExcel', ['as' => 'saveExcel', 'uses' => 'DepartmentController@saveExcel']);

    // Staff
    Route::resource('staff','StaffController');
    Route::get('change-pass/{id}',['as' => 'admin.staff.getChange', 'uses' => 'StaffController@getChange']);
    Route::post('change-pass/{id}',['as' => 'admin.staff.postChange', 'uses' => 'StaffController@postChange']);
    
    //Review
    Route::resource('review', 'ReviewController');
    Route::get('add-colnum', ['as' => 'addColnum', 'uses' => 'ReviewController@addColnum']);
    
    //Level
    Route::resource('level', 'LevelController');
    Route::get('edit-review/{idReview}/{idStaff}',['as' => 'admin.review.editReview', 'uses' => 'ReviewController@editReview']);
    Route::resource('team', 'TeamController');

    // Position
    Route::resource('position', 'PositionController');
});

Route::any('{all}', function () {
    return view('errors.503');
});
Route::any('admin/{all}', function () {
    return view('errors.503');
});

app/Level.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Level extends Model
{
    protected $table = 'level';

    protected $fillable = ['name', 'role_id'];

    public $timestamps = false;

    public function staff(){
    	return $this->hasMany('App\Staff','level_id');
    }

    public function role(){
    	return $this->belongsTo('App\Role', 'role_id');
    }
}

app/Http/Controllers/LevelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Level;
use App\Role;
use App\Staff;

class LevelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('level');
    }

    public function index()
    {
        $level = Level::where('role_id', '!=', 1)->get();
        $role = Role::where('name', '!=', 'SystemAdmin')->get();
        return view('admin.level.list', compact('level', 'role'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = Role::where('active', 1)->get();
        return view ('admin.level.create', compact('role'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'txtName' => 'required', 'role' => 'required|numeric|not_in:0','rActive' => 'required|in:0,1',
        ]);

        $level = new Level();
        $level->name = $request->txtName;
        $level->role_id = $request->role;
        $level->active = $request->rActive;
        $level->save();
        return redirect()->route('admin.level.index')->with('message', 'Create level success!');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $level = Level::find($id);
        $role = Role::where('name', '!=', 'SystemAdmin')->get();
        return view('admin.level.update', compact('level', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'txtName' => 'required', 
            'role' => 'required|numeric|not_in:0',
            'rActive' => 'required|in:0,1',
        ]);

        $level = Level::find($id);
        $level->name = $request->txtName;
        $level->role_id = $request->role;
        $level->active = $request->rActive;
        $level->save();
        return redirect()->route('admin.level.index')->with('message', 'Update level success!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $findLevel = Staff::where('level_id', $id)->get()->toArray();
        if(!empty($findLevel)){
            return redirect()->route('admin.level.index')->with('message', 'Can\'t delete level !');
        }
        $level = Level::find($id);
        $level->delete();
        return redirect()->route('admin.level.index')->with('message', 'Delete level success!');
    }
}

resources/views/admin/level/create.blade.php
@extends('admin.master')
@section('title')
Create Level
@endsection
@section('content')
<form class="form-horizontal" method="POST" action="{{ route('admin.level.store') }}">
	<input type="hidden" name="_token" value="{{ csrf_token() }}" >
	<div class="form-group form-group-sm">
    	<label class="col-sm-1"></label>
    	<div class="col-sm-7">
    		@if (count($errors) > 0)
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Name</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtName" type="text" id="formGroupInputSmall" value="{{ old('txtName') }}" placeholder="Enter Name Here ...">
    	</div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Role</label>
    	<div class="col-sm-6">
      		<select class="form-control" name="role">
      		 	<option value="0">  ------  </option>
			    @if($role)
				    @foreach($role as $key => $value)
				    	<?php echo '<option value="'.$value['id'].'" > '.$value['name'].' </option>' ?>
				    @endforeach
			    @endif
			</select>
    	</div>
    </div>
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
             Active <input type="radio" name="rActive" id="optionsRadios1" value="1" checked>
        </div>
        <div class="col-sm-2">
             DeActive <input type="radio" name="rActive" id="optionsRadios1" value="0">
        </div>
    </div>
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall"></label>
    	<div class="col-sm-6">
      		<button class="btn btn-primary" name="btnSubmit" style="width:100px">Create</button>
    	</div>
    </div>
  
</form>
@endsection

resources/views/admin/level/list.blade.php
@extends('admin.master')
@section('title')
Level
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12">
        @if(Session::has('message'))
            <div id="message" class="alert alert-success">
                {{ Session::get('message') }}
            </div>
        @endif
        <div class="panel panel-default">
            <div class="panel-heading danger">
                <p style="color:#337ab7">{{ count($level) }} Levels / {{ count($role) }} Roles</p>
            </div>
            
            <!-- /.panel-heading -->
            <div class="row">
                <div class="col-sm-6" style="margin-top:10px; margin-left:10px">
                    
                 </div>
             </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-hover table-bordered table-striped" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th><a href="">Level </a></th>
                                <th><a href="">Role </a></th>
                                <th style="text-align:center"><a href="">Status</a></th>
                                <th style="text-align:center"><a href="">Action</a></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $stt=1; ?>
                            @foreach($level as $key => $value)
                                <tr>
                                    <td>{{ $stt }}</td>
                                    <td>{{ $value->name }}</td>
                                    <td>{{ $value->role->name }}</td>
                                    <th><?php echo $value->active==1?'Active':'DeActive' ?></th>
                                    <td style="text-align:center">
                                        <label>
                                            <button class="btn btn-link"><a href="{{ route('admin.level.edit', $value->id) }}"><i class="glyphicon glyphicon-pencil"></i></a></button> &nbsp;&nbsp;&nbsp;
                                        </label>
                                        <label>
                                            {!! Form::open( array( 'route' => array('admin.level.destroy',$value->id), 'method' => 'DELETE' ) ) !!}
                                                <button onclick="return deleteConfirm('You want delete?')" type="submit"  class="btn btn-link" ><i class="glyphicon glyphicon-remove"></i></button>
                                            {!! Form::close() !!}
                                        </label>
                                    </td>
                                </tr>
                                <?php $stt++ ?>
                            @endforeach

                        </tbody>
                    </table>
                    
                </div>
                <!-- /.table-responsive -->
                
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
@endsection

resources/views/admin/level/update.blade.php
@extends('admin.master')
@section('title')
Create Level
@endsection
@section('content')
<form class="form-horizontal" method="POST" action="{{ route('admin.level.update', $level->id) }}">
	<input type="hidden" name="_method" value="PUT">
    <input type="hidden" name="_token" value="{{ csrf_token() }}" >
	<div class="form-group form-group-sm">
    	<label class="col-sm-1"></label>
    	<div class="col-sm-7">
    		@if (count($errors) > 0)
			    <div class="alert alert-danger">
			        <ul>
			            @foreach ($errors->all() as $error)
			                <li>{{ $error }}</li>
			            @endforeach
			        </ul>
			    </div>
			@endif
    	</div>
    </div>
   
    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall">Name</label>
    	<div class="col-sm-6">
      		<input class="form-control" name="txtName" type="text" id="formGroupInputSmall" value="{{ old('txtName',$level->name?$level->name:'')  }}">
    	</div>
    </div>
    
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label" for="formGroupInputSmall">Role</label>
        <div class="col-sm-6">
            <select class="form-control" name="role">
                @if($role)
                    @foreach($role as $key => $value)
                        <option value="{{ $value['id'] }}" <?php echo ($value['id'] == $level->role->id)?'selected':''  ?> >{{ $value['name'] }}</option>
                    @endforeach
                @endif
            </select>
        </div>
    </div>
    
    <div class="form-group form-group-sm">
        <label class="col-sm-2 control-label"></label>
        <div class="col-sm-2">
             Active <input type="radio" name="rActive" id="optionsRadios1" value="1" <?php echo ($level->active==1)?'checked':'' ?> >
        </div>
        <div class="col-sm-2">
             DeActive <input type="radio" name="rActive" id="optionsRadios1" value="0" <?php echo ($level->active==0)?'checked':'' ?> >
        </div>
    </div>

    <div class="form-group form-group-sm">
    	<label class="col-sm-2 control-label" for="formGroupInputSmall"></label>
    	<div class="col-sm-6">
      		<button class="btn btn-primary" name="btnSubmit" style="width:100px">Update</button>
    	</div>
    </div>
  
</form>
@endsection