app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin'] );


// Authentication routes...
Route::get('auth/login',  ['as' => 'getLogin', 'uses' => 'Auth\AuthController@getLogin']);
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');


Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
	// Department
    Route::resource('department', 'DepartmentController');
    Route::get('list', ['as' => 'admin.department.listDep', 'uses' => 'DepartmentController@listDep']);
    Route::post('savePdf', ['as' => 'savePdf', 'uses' => 'DepartmentController@savePdf']);
    Route::get('saveExcel', ['as' => 'saveExcel', 'uses' => 'DepartmentController@saveExcel']);

    // Staff
    Route::resource('staff','StaffController');
    Route::get('change-pass/{id}',['as' => 'admin.staff.getChange', 'uses' => 'StaffController@getChange']);
    Route::post('change-pass/{id}',['as' => 'admin.staff.postChange', 'uses' => 'StaffController@postChange']);
    
    //Review
    Route::resource('review', 'ReviewController');
    Route::get('add-colnum', ['as' => 'addColnum', 'uses' => 'ReviewController@addColnum']);
    
    //Level
    Route::resource('level', 'LevelController');
    Route::get('edit-review/{idReview}/{idStaff}',['as' => 'admin.review.editReview', 'uses' => 'ReviewController@editReview']);
    Route::resource('team', 'TeamController');

    // Position
    Route::resource('position', 'PositionController');
});

Route::any('{all}', function () {
    return view('errors.503');
});
Route::any('admin/{all}', function () {
    return view('errors.503');
});

resources/views/admin/inc/header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Elisoft - Staff manager</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{ asset('public/admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{{ asset('public/admin/bower_components/metisMenu/dist/metisMenu.min.css') }}" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="{{ asset('public/admin/dist/css/timeline.css') }}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{{ asset('public/admin/dist/css/sb-admin-2.css') }}" rel="stylesheet">

    
    <!-- DataTables CSS -->
    <link href="{{ asset('public/admin/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css') }}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{{ asset('public/admin/bower_components/datatables-responsive/css/dataTables.responsive.css') }}" rel="stylesheet">


    <!-- Custom Fonts -->
    <link href="{{ asset('public/admin/bower_components/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">

    <!-- Processbar CSS -->
    <link href="{{ asset('public/admin/css/bootstrap-progressbar-3.3.4.css') }}" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="{{ asset('public/admin/css/style.css') }}" rel="stylesheet">


    <!-- Jquery UI  -->
    <!-- jQuery -->
    <script src="{{ asset('public/admin/bower_components/jquery/dist/jquery.min.js') }}"></script>
    <link href="{{ asset('public/admin/jquery-ui/jquery-ui.min.css') }}" rel="stylesheet">
    <script type="text/javascript" src="{{ asset('public/admin/jquery-ui/jquery-ui.min.js') }}"></script>
    <script>
      $(function() {
        $( "#datepicker" ).datepicker({
            changeMonth: true,
            changeYear: true,
            dateFormat: "dd-mm-yy",
            yearRange: "1970:2030"
        });
      });
    </script>

    <!-- Button Jquery -->
    
    <link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.jqueryui.min.css" rel="stylesheet">

    <link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.foundation.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.jqueryui.min.css" rel="stylesheet">

    <!-- SUMO Jquery -->
    <link href="{{ asset('public/admin/sumo/sumoselect.css') }}" rel="stylesheet">
    <script src="{{ asset('public/admin/sumo/jquery.sumoselect.js') }}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Chart -->
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>

    <!-- CK editor && CK finder -->
    <script type="text/javascript" src="{{ asset('public/admin/js/ckeditor/ckeditor.js') }}"></script>
    <script type="text/javascript" src="{{ asset('public/admin/js/ckfinder/ckfinder.js') }}"></script>
    <script type="text/javascript">
        var baseURL = "{{ url('/') }}";
    </script>
    <script type="text/javascript" src="{{ asset('public/admin/js/func_ckfinder.js') }}"></script>
</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ route('admin.review.show', Auth::user()->id) }}">Staff Manager | Hello {{ Auth::user()->name }} ({{ $role }})</a> 
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                
                
                
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="{{ route('admin.staff.edit', Auth::user()->id) }}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="{{ url('auth/logout') }}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->

resources/views/admin/inc/left.blade.php
<div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="{{ route('admin.department.index') }}"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        @can('check-manager')
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Staff<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.staff.create') }}">Create Staff</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.staff.index') }}">List Staff</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Team<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.team.create') }}">Create Team</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.team.index') }}">List Team</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        @endcan
                        @can('check-leader')
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Staff<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.staff.create') }}">Create Staff</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.staff.index') }}">List Staff</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Team<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.team.create') }}">Create Team</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.team.index') }}">List Team</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        @endcan
                        @can('check-admin')
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Staff<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.staff.create') }}">Create Staff</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.staff.index') }}">List Staff</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Level<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.level.create') }}">Create Level</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.level.index') }}">List Level</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Position<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.position.create') }}">Create Position</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.position.index') }}">List Position</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Department<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="{{ route('admin.department.create') }}">Create Department</a>
                                </li>
                                <li>
                                    <a href="{{ route('admin.department.listDep') }}">List Department</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        @endcan
                        <li>
                            <a href="{{ route('admin.review.show', Auth::user()->id) }}"><i class="fa fa-edit fa-fw"></i> Review</a>
                        </li>
                        
                        
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>